<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Area Chart' => 'Аймактык диаграмманын үлгүсү',
	'Area Chart Example' => 'Аймактык диаграмма',
	'Authentication' => 'Аутентификация',
	'Bar Chart' => 'Тилкелүү диаграмманын үлгүсү',
	'Bar Chart Example' => 'Тилкелүү диаграмма',
	'Charts' => 'Диаграммалар',
	'Danger Card' => 'Коркунуч картасы',
	'DataTable Example' => 'Маалымат таблицасынын үлгүсү',
	'Error' => 'Ката',
	'Example Data Table' => 'Үлгү маалымат таблицасы',
	'Interface' => 'Интерфейс',
	'Layouts' => 'Макеттер',
	'Light Sidenav' => 'Жарык каптал меню',
	'Pages' => 'Барактар',
	'Primary Card' => 'Негизги карта',
	'Static Navigation' => 'Туруктуу навигация',
	'Success Card' => 'Ийгилик картасы',
	'Tables' => 'Таблицалар',
	'View Details' => 'Толугураак',
	'Warning Card' => 'Эскертүү картасы',
];
