<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Account' => 'Каттоо эсеби',
	'Account Settings' => 'Каттоо эсебинин жөндөөлөрү',
	'Are you sure? There is no going back' => 'Ишенесизби? Артка жол жок',
	'Bio' => 'Өзү жөнүндө',
	'Change your avatar at Gravatar.com' => 'Аватарыңызды Gravatar.com сайтынан өзгөртүңүз',
	'Delete account' => 'Каттоо эсебин өчүрүү',
	'Disable two factor authentication' => 'Эки факторлуу аутентификацияны өчүрүү',
	'Enable two factor authentication' => 'Эки факторлуу аутентификацияны күйгүзүү',
	'Gravatar Email' => 'Gravatar email',
	'It will be deleted forever' => 'Түбөлүккө өчүрүлөт',
	'Location' => 'Жайгашкан жери',
	'New Email' => 'Жаңы email',
	'Once you delete your account, there is no going back' => 'Каттоо эсебин өчүрсөңүз, артка жол жок',
	'Password' => 'Купуя сөз',
	'Password Age' => 'Купуя сөздүн жашы',
	'Password Changed' => 'Купуя сөз өзгөртүлдү',
	'Please be certain' => 'Тактаңыз',
	'Profile' => 'Профиль',
	'Profile Settings' => 'Профиль жөндөөлөрү',
	'Public Email' => 'Жалпыга ачык email',
	'Security' => 'Коопсуздук',
	'The email address set is: "{0}".' => 'Белгиленген email: «{0}».',
	'The phone number set is: "{0}".' => 'Белгиленген телефон номери: «{0}».',
	'This will disable two factor authentication. Are you sure?' => 'Бул эки факторлуу аутентификацияны өчүрөт. Ишенесизби?',
	'Timezone' => 'Убакыт алкагы',
	'Two Factor Authentication (2FA)' => 'Эки факторлуу аутентификация (2FA)',
	'Two factor authentication protects you in case of stolen credentials' => 'Эки факторлуу аутентификация маалымат уурдалса да коргойт',
	'Website' => 'Веб-сайт',
	'Your two factor authentication method is based on "{0}".' => 'Эки факторлуу ыкмаңыз — «{0}».',
];
