<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Block User' => 'Колдонуучуну бөгөттөө',
	'Delete Permission' => 'Уруксатты өчүрүү',
	'Delete Role' => 'Ролду өчүрүү',
	'Delete Rule' => 'Эрежени өчүрүү',
	'Delete User' => 'Колдонуучуну өчүрүү',
	'Edit Role' => 'Ролду түзөтүү',
	'Edit Rule' => 'Эрежени түзөтүү',
	'Permissions Actions' => 'Уруксаттар аракеттери',
	'Reset Password' => 'Сырсөздү калыбына келтирүү',
	'Role Actions' => 'Ролдор аракеттери',
	'Rule Actions' => 'Эрежелер аракеттери',
	'Select Language' => 'Тилди тандоо',
	'Switch Identity' => 'Өздүктү алмаштыруу',
	'Toggle Navigation' => 'Навигацияны которуу',
	'Update Permission' => 'Уруксатты жаңыртуу',
	'Update User' => 'Колдонуучуну жаңыртуу',
	'User Actions' => 'Колдонуучу аракеттери',
	'User avatar' => 'Колдонуучунун аватары',
	'User confirmed' => 'Колдонуучу ырасталган',
	'User is blocked' => 'Колдонуучу бөгөттөлгөн',
	'User is not blocked' => 'Колдонуучу бөгөттөлгөн эмес',
	'User Menu' => 'Колдонуучу менюсу',
	'User not confirmed' => 'Колдонуучу ырасталган эмес',
	'View User' => 'Колдонуучуну көрүү',
];
