<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Actions' => 'Аракеттер',
	'Age' => 'Жашы',
	'Are you sure you want to delete this item?' => 'Бул элементти өчүргүңүз келгенине ишенесизби?',
	'Are you sure?' => 'Ишенесизби?',
	'Cancel' => 'Жокко чыгаруу',
	'Class' => 'Класс',
	'Created' => 'Түзүлгөн',
	'Delete' => 'Өчүрүү',
	'Description' => 'Сүрөттөмө',
	'Email' => 'Электрондук почта',
	'Last Login' => 'Акыркы кирүү',
	'Last Login IP' => 'Акыркы кирүү IP',
	'Logged in as:' => 'Кирген колдонуучу:',
	'Name' => 'Аты',
	'No' => 'Жок',
	'Office' => 'Офис',
	'Position' => 'Кызматы',
	'Registration IP' => 'Катталуу IP',
	'Salary' => 'Айлык',
	'Save' => 'Сактоо',
	'Search' => 'Издөө',
	'Settings' => 'Жөндөөлөр',
	'Start Date' => 'Башталган күнү',
	'Update' => 'Жаңыртуу',
	'Updated' => 'Жаңыртылган',
	'Username' => 'Колдонуучунун аты',
	'Yes' => 'Ооба',
];
