<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Age' => 'Жашы',
    'Area Chart Example' => 'Аймактык диаграмманын үлгүсү',
    'Area chart' => 'Аймактык диаграмма',
    'Bar Chart Example' => 'Тилкелүү диаграмманын үлгүсү',
    'Bar chart' => 'Тилкелүү диаграмма',
    'Danger Card' => 'Коркунуч картасы',
    'DataTable Example' => 'Маалымат таблицасынын үлгүсү',
    'Example data table' => 'Үлгү маалымат таблицасы',
    'Name' => 'Аты',
    'Office' => 'Офис',
    'Overview' => '@@Overview@@',
    'Position' => 'Кызматы',
    'Primary Card' => 'Негизги карта',
    'Recent activity' => '@@Recent activity@@',
    'Salary' => 'Айлык',
    'Start date' => 'Башталган күнү',
    'Success Card' => 'Ийгилик картасы',
    'System status' => '@@System status@@',
    'View Details' => 'Толугураак',
    'Warning Card' => 'Эскертүү картасы',
];
