<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Area Chart' => 'Area Chart',
	'Area Chart Example' => 'Area Chart Example',
	'Authentication' => 'Authentication',
	'Bar Chart' => 'Bar Chart',
	'Bar Chart Example' => 'Bar Chart Example',
	'Charts' => 'Charts',
	'Danger Card' => 'Danger Card',
	'DataTable Example' => 'DataTable Example',
	'Error' => 'Error',
	'Example Data Table' => 'Example Data Table',
	'Interface' => 'Interface',
	'Layouts' => 'Layouts',
	'Light Sidenav' => 'Light Sidenav',
	'Pages' => 'Pages',
	'Primary Card' => 'Primary Card',
	'Static Navigation' => 'Static Navigation',
	'Success Card' => 'Success Card',
	'Tables' => 'Tables',
	'View Details' => 'View Details',
	'Warning Card' => 'Warning Card',
];
