<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Block User' => 'Foydalanuvchini bloklash',
    'Delete Permission' => 'Ruxsatni o‘chirish',
    'Delete Role' => 'Rolni o‘chirish',
    'Delete Rule' => 'Qoidani o‘chirish',
    'Delete User' => 'Foydalanuvchini o‘chirish',
    'Edit Role' => 'Rolni tahrirlash',
    'Edit Rule' => 'Qoidani tahrirlash',
    'Permissions Actions' => 'Ruxsatlar bilan amallar',
    'Profile photo of {username}' => '',
    'Resend confirmation email' => 'Tasdiqlash xatini qayta yuborish',
    'Reset Password' => 'Parolni tiklash',
    'Role Actions' => 'Rollar bilan amallar',
    'Rule Actions' => 'Qoidalar bilan amallar',
    'Select Language' => '@@Tilni tanlash@@',
    'Select language' => '',
    'Submit login form' => 'Kirish formasini yuborish',
    'Switch Identity' => 'Shaxsni almashtirish',
    'Toggle Navigation' => 'Navigatsiyani almashtirish',
    'Update Permission' => 'Ruxsatni yangilash',
    'Update User' => 'Foydalanuvchini yangilash',
    'User Actions' => 'Foydalanuvchi amallari',
    'User Details' => 'Foydalanuvchi maʼlumotlari',
    'User Menu' => 'Foydalanuvchi menyusi',
    'User Settings Navigation' => 'Foydalanuvchi sozlamalari navigatsiyasi',
    'User avatar' => '',
    'User confirmed' => 'Foydalanuvchi tasdiqlangan',
    'User is blocked' => 'Foydalanuvchi bloklangan',
    'User is not blocked' => 'Foydalanuvchi bloklanmagan',
    'User not confirmed' => 'Foydalanuvchi tasdiqlanmagan',
    'View User' => 'Foydalanuvchini ko‘rish',
];
