<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Block User' => 'Корбарро маҳкам кардан',
	'Delete Permission' => 'Иҷозатро нест кардан',
	'Delete Role' => 'Нақшро нест кардан',
	'Delete Rule' => 'Қоидаро нест кардан',
	'Delete User' => 'Корбарро нест кардан',
	'Edit Role' => 'Таҳрири нақш',
	'Edit Rule' => 'Таҳрири қоида',
	'Permissions Actions' => 'Амалиёти ҳуқуқҳо',
	'Reset Password' => 'Барқарорсозии парол',
	'Role Actions' => 'Амалиёти нақшҳо',
	'Rule Actions' => 'Амалиёти қоидаҳо',
	'Select Language' => 'Интихоби забон',
	'Switch Identity' => 'Иваз кардани шахсият',
	'Toggle Navigation' => 'Навигатсияро иваз кардан',
	'Update Permission' => 'Навсозии иҷозат',
	'Update User' => 'Навсозии корбар',
	'User Actions' => 'Амалиёти корбар',
	'User avatar' => 'Аватари корбар',
	'User confirmed' => 'Корбар тасдиқ шудааст',
	'User is blocked' => 'Корбар баста шудааст',
	'User is not blocked' => 'Корбар баста нашудааст',
	'User Menu' => 'Менюи корбар',
	'User not confirmed' => 'Корбар тасдиқ нашудааст',
	'View User' => 'Дидани корбар',
];
