<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Block User' => 'Заблокировать пользователя',
    'Delete Permission' => 'Удалить разрешение',
    'Delete Role' => 'Удалить роль',
    'Delete Rule' => 'Удалить правило',
    'Delete User' => 'Удалить пользователя',
    'Edit Role' => 'Редактировать роль',
    'Edit Rule' => 'Редактировать правило',
    'Permissions Actions' => 'Действия с правами',
    'Profile photo of {username}' => '',
    'Resend confirmation email' => 'Повторно отправить письмо с подтверждением',
    'Reset Password' => 'Сбросить пароль',
    'Role Actions' => 'Действия с ролями',
    'Rule Actions' => 'Действия с правилами',
    'Select Language' => '@@Выбрать язык@@',
    'Select language' => '',
    'Submit login form' => 'Отправить форму входа',
    'Switch Identity' => 'Сменить личность',
    'Toggle Navigation' => 'Переключить навигацию',
    'Update Permission' => 'Жаңарту рұқсаты',
    'Update User' => 'Обновить пользователя',
    'User Actions' => 'Действия пользователя',
    'User Details' => 'Данные пользователя',
    'User Menu' => 'Меню пользователя',
    'User Settings Navigation' => 'Навигация настроек пользователя',
    'User avatar' => '',
    'User confirmed' => 'Пользователь подтверждён',
    'User is blocked' => 'Пользователь заблокирован',
    'User is not blocked' => 'Пользователь не заблокирован',
    'User not confirmed' => 'Пользователь не подтверждён',
    'View User' => 'Просмотреть пользователя',
];
