<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Block User' => 'Пайдаланушыны бұғаттау',
	'Delete Permission' => 'Рұқсатты жою',
	'Delete Role' => 'Рөлді жою',
	'Delete Rule' => 'Ережені жою',
	'Delete User' => 'Пайдаланушыны жою',
	'Edit Role' => 'Рөлді өңдеу',
	'Edit Rule' => 'Ережені өңдеу',
	'Permissions Actions' => 'Рұқсаттар әрекеттері',
	'Reset Password' => 'Құпиясөзді қалпына келтіру',
	'Role Actions' => 'Рөлдер әрекеттері',
	'Rule Actions' => 'Ережелер әрекеттері',
	'Select Language' => 'Тілді таңдау',
	'Switch Identity' => 'Тұлғаны ауыстыру',
	'Toggle Navigation' => 'Навигацияны ауыстыру',
	'Update Permission' => 'Рұқсатты жаңарту',
	'Update User' => 'Пайдаланушыны жаңарту',
	'User Actions' => 'Пайдаланушы әрекеттері',
	'User avatar' => 'Пайдаланушы аватары',
	'User confirmed' => 'Пайдаланушы расталған',
	'User is blocked' => 'Пайдаланушы бұғатталған',
	'User is not blocked' => 'Пайдаланушы бұғатталмаған',
	'User Menu' => 'Пайдаланушы мәзірі',
	'User not confirmed' => 'Пайдаланушы расталмаған',
	'View User' => 'Пайдаланушыны қарау',
];
