<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Area Chart' => 'Аймақтық диаграмма үлгісі',
	'Area Chart Example' => 'Аймақтық диаграмма',
	'Authentication' => 'Аутентификация',
	'Bar Chart' => 'Бағанды диаграмма үлгісі',
	'Bar Chart Example' => 'Бағанды диаграмма',
	'Charts' => 'Диаграммалар',
	'Danger Card' => 'Қауіп картасы',
	'DataTable Example' => 'Деректер кестесінің үлгісі',
	'Error' => 'Қате',
	'Example Data Table' => 'Үлгі деректер кестесі',
	'Interface' => 'Интерфейс',
	'Layouts' => 'Макеттер',
	'Light Sidenav' => 'Жарық бүйірлік мәзір',
	'Pages' => 'Беттер',
	'Primary Card' => 'Негізгі карта',
	'Static Navigation' => 'Тұрақты навигация',
	'Success Card' => 'Сәттілік картасы',
	'Tables' => 'Кестелер',
	'View Details' => 'Толығырақ',
	'Warning Card' => 'Ескерту картасы',
];
