<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Area Chart' => 'Maydonli diagramma namunasi',
	'Area Chart Example' => 'Maydonli diagramma',
	'Authentication' => 'Autentifikatsiya',
	'Bar Chart' => 'Ustunli diagramma namunasi',
	'Bar Chart Example' => 'Ustunli diagramma',
	'Charts' => 'Diagrammalar',
	'Danger Card' => 'Xavf kartasi',
	'DataTable Example' => 'Ma’lumotlar jadvali namunasi',
	'Error' => 'Xato',
	'Example Data Table' => 'Namunaviy ma’lumotlar jadvali',
	'Interface' => 'Interfeys',
	'Layouts' => 'Makетlar',
	'Light Sidenav' => 'Yorug‘ yon menyu',
	'Pages' => 'Sahifalar',
	'Primary Card' => 'Asosiy karta',
	'Static Navigation' => 'Statik navigatsiya',
	'Success Card' => 'Muvaffaqiyat kartasi',
	'Tables' => 'Jadvallar',
	'View Details' => 'Batafsil',
	'Warning Card' => 'Ogohlantirish kartasi',
];
