<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Add Permission' => 'Ruxsat qo‘shish',
	'Add Role' => 'Rol qo‘shish',
	'Add Rule' => 'Qoida qo‘shish',
	'Add User' => 'Foydalanuvchi qo‘shish',
	'Blocked' => 'Bloklangan',
	'Confirmed' => 'Tasdiqlangan',
	'Manage Permissions' => 'Kirish ruxsatlarini boshqarish',
	'Manage Roles' => 'Rollarni boshqarish',
	'Manage Rules' => 'Qoidalarni boshqarish',
	'Manage Users' => 'Foydalanuvchilarni boshqarish',
	'Rule Name' => 'Qoida nomi',
	'Status' => '@@Holat@@',
	'User Profile' => '@@Foydalanuvchi profili@@',
	'View' => '@@Ko‘rish@@',
];
