<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Account' => 'Hisob',
	'Account Settings' => 'Hisob sozlamalari',
	'Are you sure? There is no going back' => 'Ishonchingiz komilmi? Orqaga yo‘l yo‘q',
	'Bio' => 'O‘zim haqimda',
	'Change your avatar at Gravatar.com' => 'Gravatar.com’da avataringizni o‘zgartiring',
	'Delete account' => 'Hisobni o‘chirish',
	'Disable two factor authentication' => 'Ikki bosqichli tasdiqlashni o‘chirish',
	'Enable two factor authentication' => 'Ikki bosqichli tasdiqlashni yoqish',
	'Gravatar Email' => 'Gravatar email',
	'It will be deleted forever' => 'U butunlay o‘chiriladi',
	'Location' => 'Joylashuv',
	'New Email' => 'Yangi email',
	'Once you delete your account, there is no going back' => 'Hisobni o‘chirsangiz, orqaga yo‘l yo‘q',
	'Password' => 'Parol',
	'Password Age' => 'Parol yoshi',
	'Password Changed' => 'Parol o‘zgartirildi',
	'Please be certain' => 'Iltimos, ishonch hosil qiling',
	'Profile' => 'Profil',
	'Profile Settings' => 'Profil sozlamalari',
	'Public Email' => 'Ochiq email',
	'Security' => 'Xavfsizlik',
	'The email address set is: "{0}".' => 'Kiritilgan email manzil: “{0}”.',
	'The phone number set is: "{0}".' => 'Kiritilgan telefon raqam: “{0}”.',
	'This will disable two factor authentication. Are you sure?' => 'Bu ikki bosqichli tasdiqlashni o‘chiradi. Ishonchingiz komilmi?',
	'Timezone' => 'Vaqt mintaqasi',
	'Two Factor Authentication (2FA)' => 'Ikki bosqichli tasdiqlash (2FA)',
	'Two factor authentication protects you in case of stolen credentials' => 'Ikki bosqichli tasdiqlash ma’lumotlar o‘g‘irlanganda sizni himoya qiladi',
	'Website' => 'Veb-sayt',
	'Your two factor authentication method is based on "{0}".' => '2FA usulingiz: “{0}”.',
];
