<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Actions' => 'Amallar',
	'Age' => 'Yosh',
	'Are you sure you want to delete this item?' => 'Ushbu elementni o‘chirmoqchi ekaningizga ishonchingiz komilmi?',
	'Are you sure?' => 'Ishonchingiz komilmi?',
	'Cancel' => 'Bekor qilish',
	'Class' => 'Sinf',
	'Created' => 'Yaratilgan',
	'Delete' => 'O‘chirish',
	'Description' => 'Tavsif',
	'Email' => 'Elektron pochta',
	'Last Login' => 'So‘nggi kirish',
	'Last Login IP' => 'So‘nggi kirish IP',
	'Logged in as:' => 'Kirish:',
	'Name' => 'Ism',
	'No' => 'Yo‘q',
	'Office' => 'Ofis',
	'Position' => 'Lavozim',
	'Registration IP' => 'Ro‘yxatdan o‘tish IP',
	'Salary' => 'Maosh',
	'Save' => 'Saqlash',
	'Search' => 'Qidirish',
	'Settings' => 'Sozlamalar',
	'Start Date' => 'Boshlanish sanasi',
	'Update' => 'Yangilash',
	'Updated' => 'Yangilandi',
	'Username' => 'Foydalanuvchi nomi',
	'Yes' => 'Ha',
];
