<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Account' => 'Аккаунт',
	'Account Settings' => 'Настройки аккаунта',
	'Are you sure? There is no going back' => 'Вы уверены? Пути назад нет',
	'Bio' => 'О себе',
	'Change your avatar at Gravatar.com' => 'Изменить аватар на Gravatar.com',
	'Delete account' => 'Удалить аккаунт',
	'Disable two factor authentication' => 'Отключить двухфакторную аутентификацию',
	'Enable two factor authentication' => 'Включить двухфакторную аутентификацию',
	'Gravatar Email' => 'Email для Gravatar',
	'It will be deleted forever' => 'Он будет удалён навсегда',
	'Location' => 'Местоположение',
	'New Email' => 'Новый email',
	'Once you delete your account, there is no going back' => 'После удаления аккаунта пути назад нет',
	'Password' => 'Пароль',
	'Password Age' => 'Возраст пароля',
	'Password Changed' => 'Пароль изменён',
	'Please be certain' => 'Пожалуйста, убедитесь',
	'Profile' => 'Профиль',
	'Profile Settings' => 'Настройки профиля',
	'Public Email' => 'Публичный email',
	'Security' => 'Безопасность',
	'The email address set is: "{0}".' => 'Указан адрес электронной почты: «{0}».',
	'The phone number set is: "{0}".' => 'Указан номер телефона: «{0}».',
	'This will disable two factor authentication. Are you sure?' => 'Это отключит двухфакторную аутентификацию. Вы уверены?',
	'Timezone' => 'Часовой пояс',
	'Two Factor Authentication (2FA)' => 'Двухфакторная аутентификация (2FA)',
	'Two factor authentication protects you in case of stolen credentials' => 'Двухфакторная аутентификация защищает вас в случае кражи учётных данных',
	'Website' => 'Веб-сайт',
	'Your two factor authentication method is based on "{0}".' => 'Ваш метод двухфакторной аутентификации — «{0}».',
];
