<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Actions' => 'Действия',
	'Age' => 'Возраст',
	'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить этот элемент?',
	'Are you sure?' => 'Вы уверены?',
	'Cancel' => '@@Отмена@@',
	'Class' => 'Класс',
	'Created' => 'Создан',
	'Delete' => '@@Удалить@@',
	'Description' => 'Описание',
	'Email' => 'Электронная почта',
	'Logged in as:' => 'Вы вошли как:',
	'Name' => 'Имя',
	'No' => 'Нет',
	'Office' => 'Офис',
	'Position' => 'Должность',
	'Salary' => 'Зарплата',
	'Save' => '@@Сохранить@@',
	'Search' => 'Поиск',
	'Start Date' => 'Дата начала',
	'Update' => '@@Обновить@@',
	'Updated' => 'Обновлено',
	'Username' => 'Имя пользователя',
	'Yes' => 'Да',
];
