<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Age' => 'Возраст',
    'Area Chart Example' => 'Пример областного графика',
    'Area chart' => 'Областной график',
    'Bar Chart Example' => 'Пример столбчатого графика',
    'Bar chart' => 'Столбчатый график',
    'Danger Card' => 'Карточка: опасность',
    'DataTable Example' => 'Пример таблицы данных',
    'Example data table' => 'Пример таблицы данных',
    'Name' => 'Имя',
    'Office' => 'Офис',
    'Overview' => '@@Overview@@',
    'Position' => 'Должность',
    'Primary Card' => 'Карточка: основная',
    'Recent activity' => '@@Recent activity@@',
    'Salary' => 'Зарплата',
    'Start date' => 'Дата начала',
    'Success Card' => 'Карточка: успех',
    'System status' => '@@System status@@',
    'View Details' => 'Подробнее',
    'Warning Card' => 'Карточка: предупреждение',
];
