<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Age' => 'Age',
    'Area Chart Example' => 'Area Chart Example',
    'Area chart' => 'Area chart',
    'Bar Chart Example' => 'Bar Chart Example',
    'Bar chart' => 'Bar chart',
    'Danger Card' => 'Danger Card',
    'DataTable Example' => 'DataTable Example',
    'Example data table' => 'Example data table',
    'Name' => 'Name',
    'Office' => 'Office',
    'Overview' => '@@Overview@@',
    'Position' => 'Position',
    'Primary Card' => 'Primary Card',
    'Recent activity' => '@@Recent activity@@',
    'Salary' => 'Salary',
    'Start date' => 'Start date',
    'Success Card' => 'Success Card',
    'System status' => '@@System status@@',
    'View Details' => 'View Details',
    'Warning Card' => 'Warning Card',
];
