<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Actions' => 'Actions',
	'Age' => 'Age',
	'Are you sure you want to delete this item?' => 'Are you sure you want to delete this item?',
	'Are you sure?' => 'Are you sure?',
	'Cancel' => 'Cancel',
	'Class' => 'Class',
	'Created' => 'Created',
	'Delete' => 'Delete',
	'Description' => 'Description',
	'Email' => 'Email',
	'Last Login' => 'Last Login',
	'Last Login IP' => 'Last Login IP',
	'Logged in as:' => 'Logged in as:',
	'Name' => 'Name',
	'No' => 'No',
	'Office' => 'Office',
	'Position' => 'Position',
	'Registration IP' => 'Registration IP',
	'Salary' => 'Salary',
	'Save' => 'Save',
	'Search' => 'Search',
	'Settings' => 'Settings',
	'Start Date' => 'Start Date',
	'Update' => 'Update',
	'Updated' => 'Updated',
	'Username' => 'Username',
	'Yes' => 'Yes',
];
