<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Activity Log' => 'Activity Log',
	'Addons' => 'Addons',
	'Authentication' => 'Authentication',
	'Charts' => 'Charts',
	'Core' => 'Core',
	'Dashboard' => 'Dashboard',
	'Error' => 'Error',
	'Interface' => 'Interface',
	'Language' => 'Language',
	'Layouts' => 'Layouts',
	'Light Sidenav' => 'Light Sidenav',
	'Logged in as:' => 'Logged in as:',
	'Logout' => 'Logout',
	'Manage Users' => 'Manage Users',
	'Pages' => 'Pages',
	'Permissions' => 'Permissions',
	'Roles' => 'Roles',
	'Rules' => 'Rules',
	'Select language' => 'Select language',
	'Settings' => 'Settings',
	'Static Navigation' => 'Static Navigation',
	'Tables' => 'Tables',
	'Toggle navigation' => 'Toggle navigation',
	'User menu' => 'User menu',
	'Users' => 'Users',
];
