<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Account Settings' => 'Account Settings',
	'Account' => 'Account',
	'Are you sure? There is no going back' => 'Are you sure? There is no going back',
	'Bio' => 'Bio',
	'Change your avatar at Gravatar.com' => 'Change your avatar at Gravatar.com',
	'Delete account' => 'Delete account',
	'Disable two factor authentication' => 'Disable two factor authentication',
	'Enable two factor authentication' => 'Enable two factor authentication',
	'Gravatar Email' => 'Gravatar Email',
	'It will be deleted forever' => 'It will be deleted forever',
	'Location' => 'Location',
	'New Email' => 'New Email',
	'Once you delete your account, there is no going back' => 'Once you delete your account, there is no going back',
	'Password Age' => 'Password Age',
	'Password Changed' => 'Password Changed',
	'Password' => 'Password',
	'Please be certain' => 'Please be certain',
	'Profile Settings' => 'Profile Settings',
	'Profile' => 'Profile',
	'Public Email' => 'Public Email',
	'Security' => 'Security',
	'The email address set is: "{0}".' => 'The email address set is: "{0}".',
	'The phone number set is: "{0}".' => 'The phone number set is: "{0}".',
	'This will disable two factor authentication. Are you sure?' => 'This will disable two factor authentication. Are you sure?',
	'Timezone' => 'Timezone',
	'Two Factor Authentication (2FA)' => 'Two Factor Authentication (2FA)',
	'Two factor authentication protects you in case of stolen credentials' => 'Two factor authentication protects you in case of stolen credentials',
	'Website' => 'Website',
	'Your two factor authentication method is based on "{0}".' => 'Your two factor authentication method is based on "{0}".',
];
