<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activity Log' => 'Журнал активности',
    'Addons' => '@@Дополнения@@',
    'Authentication (placeholder)' => '@@Аутентификация (заглушка)@@',
    'Charts' => '@@Графики@@',
    'Core' => '@@Основное@@',
    'Dashboard' => '@@Панель@@',
    'Error (placeholder)' => '@@Ошибка (заглушка)@@',
    'Interface' => '@@Интерфейс@@',
    'Language' => 'Язык',
    'Layouts' => '@@Макеты@@',
    'Light Sidenav' => '@@Светлая боковая панель@@',
    'Log out' => '',
    'Logged in as:' => '@@Вы вошли как:@@',
    'Logout' => 'Выйти',
    'Manage Users' => '@@Управление пользователями@@',
    'Pages' => '@@Страницы@@',
    'Permissions' => '@@Разрешения@@',
    'Roles' => '@@Роли@@',
    'Rules' => '@@Правила@@',
    'Select language' => '',
    'Settings' => 'Настройки',
    'Static Navigation' => '@@Статическая навигация@@',
    'Tables' => '@@Таблицы@@',
    'Toggle navigation' => '',
    'User menu' => '',
    'Users' => '@@Пользователи@@',
];
