<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Account' => 'Ҳисоб',
	'Account Settings' => 'Танзимоти ҳисоб',
	'Are you sure? There is no going back' => 'Бовар доред? Бозгашт нест',
	'Bio' => 'Дар бораи худ',
	'Change your avatar at Gravatar.com' => 'Аватари худро дар Gravatar.com иваз кунед',
	'Delete account' => 'Нест кардани ҳисоб',
	'Disable two factor authentication' => 'Хомӯш кардани аутентификатсияи дуомилӣ',
	'Enable two factor authentication' => 'Фаъол кардани аутентификатсияи дуомилӣ',
	'Gravatar Email' => 'Email барои Gravatar',
	'It will be deleted forever' => 'Барои ҳамеша нест мешавад',
	'Location' => 'Ҷойгиршавӣ',
	'New Email' => 'Email-и нав',
	'Once you delete your account, there is no going back' => 'Пас аз нест кардани ҳисоб бозгашт нест',
	'Password' => 'Парол',
	'Password Age' => 'Синни парол',
	'Password Changed' => 'Парол иваз шуд',
	'Please be certain' => 'Итминон ҳосил кунед',
	'Profile' => 'Профил',
	'Profile Settings' => 'Танзимоти профил',
	'Public Email' => 'Email-и умумӣ',
	'Security' => 'Амният',
	'The email address set is: "{0}".' => 'Суроғаи email: «{0}».',
	'The phone number set is: "{0}".' => 'Рақами телефон: «{0}».',
	'This will disable two factor authentication. Are you sure?' => 'Ин аутентификатсияи дуомилиро хомӯш мекунад. Бовар доред?',
	'Timezone' => 'Минтақаи вақт',
	'Two Factor Authentication (2FA)' => 'Аутентификатсияи дуомилӣ (2FA)',
	'Two factor authentication protects you in case of stolen credentials' => 'Аутентификатсияи дуомилӣ шуморо дар ҳолати дуздида шудани маълумот ҳифз мекунад',
	'Website' => 'Вебсайт',
	'Your two factor authentication method is based on "{0}".' => 'Усули 2FA-и шумо «{0}» аст.',
];
