<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Area Chart' => 'Намунаи диаграммаи минтақавӣ',
	'Area Chart Example' => 'Диаграммаи минтақавӣ',
	'Authentication' => 'Аутентификатсия',
	'Bar Chart' => 'Намунаи диаграммаи сутунӣ',
	'Bar Chart Example' => 'Диаграммаи сутунӣ',
	'Charts' => 'Диаграммаҳо',
	'Danger Card' => 'Корти хатар',
	'DataTable Example' => 'Намунаи ҷадвали маълумот',
	'Error' => 'Хато',
	'Example Data Table' => 'Намунаи ҷадвали маълумот',
	'Interface' => 'Интерфейс',
	'Layouts' => 'Нақшаҳо',
	'Light Sidenav' => 'Менюи паҳлӯии равшан',
	'Pages' => 'Саҳифаҳо',
	'Primary Card' => 'Корти асосӣ',
	'Static Navigation' => 'Навигатсияи статикӣ',
	'Success Card' => 'Корти муваффақият',
	'Tables' => 'Ҷадвалҳо',
	'View Details' => 'Муфассал',
	'Warning Card' => 'Корти огоҳӣ',
];
