<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Age' => 'Синну сол',
    'Area Chart Example' => 'Намунаи диаграммаи минтақавӣ',
    'Area chart' => 'Диаграммаи минтақавӣ',
    'Bar Chart Example' => 'Намунаи диаграммаи сутунӣ',
    'Bar chart' => 'Диаграммаи сутунӣ',
    'Danger Card' => 'Корти хатар',
    'DataTable Example' => 'Намунаи ҷадвали маълумот',
    'Example data table' => 'Намунаи ҷадвали маълумот',
    'Name' => 'Ном',
    'Office' => 'Идора',
    'Overview' => '@@Overview@@',
    'Position' => 'Вазифа',
    'Primary Card' => 'Корти асосӣ',
    'Recent activity' => '@@Recent activity@@',
    'Salary' => 'Маош',
    'Start date' => 'Санаи оғоз',
    'Success Card' => 'Корти муваффақият',
    'System status' => '@@System status@@',
    'View Details' => 'Муфассал',
    'Warning Card' => 'Корти огоҳӣ',
];
