<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Account' => 'Есептік жазба',
	'Account Settings' => 'Есептік жазба баптаулары',
	'Are you sure? There is no going back' => 'Сенімдісіз бе? Қайтар жол жоқ',
	'Bio' => 'Өзі туралы',
	'Change your avatar at Gravatar.com' => 'Аватарыңызды Gravatar.com сайтында өзгертіңіз',
	'Delete account' => 'Есептік жазбаны жою',
	'Disable two factor authentication' => 'Екі факторлы аутентификацияны өшіру',
	'Enable two factor authentication' => 'Екі факторлы аутентификацияны қосу',
	'Gravatar Email' => 'Gravatar email',
	'It will be deleted forever' => 'Мәңгілікке жойылады',
	'Location' => 'Орналасқан жері',
	'New Email' => 'Жаңа email',
	'Once you delete your account, there is no going back' => 'Есептік жазбаны жойсаңыз, қайтар жол жоқ',
	'Password' => 'Құпиясөз',
	'Password Age' => 'Құпиясөз жасы',
	'Password Changed' => 'Құпиясөз өзгертілді',
	'Please be certain' => 'Нақты көз жеткізіңіз',
	'Profile' => 'Профиль',
	'Profile Settings' => 'Профиль баптаулары',
	'Public Email' => 'Қоғамдық email',
	'Security' => 'Қауіпсіздік',
	'The email address set is: "{0}".' => 'Көрсетілген email: «{0}».',
	'The phone number set is: "{0}".' => 'Көрсетілген телефон нөмірі: «{0}».',
	'This will disable two factor authentication. Are you sure?' => 'Бұл екі факторлы аутентификацияны өшіреді. Сенімдісіз бе?',
	'Timezone' => 'Уақыт белдеуі',
	'Two Factor Authentication (2FA)' => 'Екі факторлы аутентификация (2FA)',
	'Two factor authentication protects you in case of stolen credentials' => 'Екі факторлы аутентификация деректер ұрланған жағдайда қорғайды',
	'Website' => 'Веб-сайт',
	'Your two factor authentication method is based on "{0}".' => 'Екі факторлы аутентификация әдісіңіз — «{0}».',
];
