<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Age' => 'Жасы',
    'Area Chart Example' => 'Аймақтық диаграмма үлгісі',
    'Area chart' => 'Аймақтық диаграмма',
    'Bar Chart Example' => 'Бағанды диаграмма үлгісі',
    'Bar chart' => 'Бағанды диаграмма',
    'Danger Card' => 'Қауіп картасы',
    'DataTable Example' => 'Деректер кестесінің үлгісі',
    'Example data table' => 'Үлгі деректер кестесі',
    'Name' => 'Аты',
    'Office' => 'Кеңсе',
    'Overview' => '@@Overview@@',
    'Position' => 'Лауазымы',
    'Primary Card' => 'Негізгі карта',
    'Recent activity' => '@@Recent activity@@',
    'Salary' => 'Жалақы',
    'Start date' => 'Басталу күні',
    'Success Card' => 'Сәттілік картасы',
    'System status' => '@@System status@@',
    'View Details' => 'Толығырақ',
    'Warning Card' => 'Ескерту картасы',
];
