<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Actions' => 'Әрекеттер',
	'Age' => 'Жасы',
	'Are you sure you want to delete this item?' => 'Бұл элементті жойғыңыз келетініне сенімдісіз бе?',
	'Are you sure?' => 'Сіз сенімдісіз бе?',
	'Cancel' => '@@Болдырмау@@',
	'Class' => 'Сынып',
	'Created' => 'Жасалған',
	'Delete' => '@@Жою@@',
	'Description' => 'Сипаттама',
	'Email' => 'Электрондық пошта',
	'Logged in as:' => 'Кіру:',
	'Name' => 'Аты',
	'No' => 'Жоқ',
	'Office' => 'Кеңсе',
	'Position' => 'Лауазымы',
	'Salary' => 'Жалақы',
	'Save' => '@@Сақтау@@',
	'Search' => 'Іздеу',
	'Start Date' => 'Басталу күні',
	'Update' => '@@Жаңарту@@',
	'Updated' => 'Жаңартылды',
	'Username' => 'Пайдаланушы аты',
	'Yes' => 'Иә',
];
